### ISSUE TITLE
Usage of dev in README example

### ISSUE THREAD

**Issue by ajasmin** [dolfinus/setuptools-git-versioning#10]
According to the config shown in README.md, a build done after the 0.1.0 release would be 0.1.0.dev1...

My understanding is that "dev" in PEP440 denotes a pre-release so that the commit following 0.1.0 might be considered an older version.

I'm wondering if "0.1.0.pos1" might be better but I stand to be corrected.

**Comment by dolfinus** [comment]
Hello.

You're right, default value for `dev_template` and `dirty_template` options were wrong.
I've updated README.md to fix this and also to cover all the usages example. Could you please check it?
