### ISSUE TITLE
Possible to add a way to the CLI to get versioning without setup.py?

### ISSUE THREAD

**Issue by nkuehnle** [dolfinus/setuptools-git-versioning#101]
I'm interested in using this just as a convenient tool to get the types of version strings that this project generates in a lightweight way to tag Dockerfiles. Is there a way to do this or is the only way to setup a mock setup.py file?

**Comment by dolfinus** [comment]
https://setuptools-git-versioning.readthedocs.io/en/stable/command.html

**Comment by nkuehnle** [comment]
Thanks! That's kind of the extent of what I figured was possible. Still a very useful feature. I just made a small mock pyproject.toml and this is sufficient to make things work.
