### ISSUE TITLE
Use with setup.py bdist_wheel and Python wheels?

### ISSUE THREAD

**Issue by nkuehnle** [dolfinus/setuptools-git-versioning#102]
I'm not too familiar with the way in which wheels actually function, but I am wondering if it's at all possible to use this with a wheel? Right now if you use steptools-git-versioning, if you build a wheel it gets version 0.0.0. Is there any recipe or workaround for this to keep behavior consistent if I build the wheel from a repo and then distribute just that wheel?

**Comment by dolfinus** [comment]
> if it's at all possible to use this with a wheel

Why it should not be possible? Wheel version is calculated during the built, where .git folder is present. After .wheel file is build, it does not include `setuptools-git-versioning` at all.

**Comment by nkuehnle** [comment]
Ah interesting, I am getting behavior where it is not applying the same version when I create a wheel using  `python setup.py bdist_wheel` with as with `pip install .` I'll try to debug briefly a bit more on my end and see if I can create a minimum reproducible example later or if it's just soemthing odd that I've done. The code in question is proprietary/on my company's GH enterprise repo.

**Comment by dolfinus** [comment]
Could you give at least the config example?
