### ISSUE TITLE
Ignore unclosed TOML

### ISSUE THREAD

**Issue by zwillikon** [dolfinus/setuptools-git-versioning#105]
Hi Dolfinus,

may you please introduce an option to ignore unclosed (invalid) TOML?

When building https://github.com/pysal/esda for Python 3.10 I'm getting the same issue as https://github.com/dolfinus/setuptools-git-versioning/issues/86

I've tried updating from 1.13.3.r7.g98b350a to 2.0.0 but it wasn't a fix.

```
File "/usr/lib/python3.10/site-packages/setuptools_git_versioning.py", line 187, in _read_toml
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

[..]

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/lib/python3.10/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/lib/python3.10/site-packages/toml/decoder.py", line 849, in load_value
    raise ValueError("Found tokens after a closed " +
ValueError: Found tokens after a closed string. Invalid TOML.
```

**Comment by dolfinus** [comment]
Why do you have invalid `pyproject.toml` in the first place?

**Comment by zwillikon** [comment]
> Why do you have invalid `pyproject.toml` in the first place?

It isn't mine. There are a lot Github repositories with such files.

**Comment by dolfinus** [comment]
Why does those "lots of repositories" affect building a specific package?

**Comment by zwillikon** [comment]
You can close this issue, I know how to patch your program.
