### ISSUE TITLE
Not recognizing latest Git tag

### ISSUE THREAD

**Issue by dhathris** [dolfinus/setuptools-git-versioning#22]
I have project that I am packaging using setuptools-git-versioning based on Git tags. 
I have a `staging` branch that is stable and a `feature/myfeature` branch created from staging. 
Now `staging` branch has the existing tag `v0.0.0rc1`. 
And I created a new Git tag on `feature/myfeature` branch, called `v0.0.0b1`. Note the this tag is created AFTER `v0.0.0rc1` tag on the `staging` branch.
I run the command `python3 setup.py sdist bdist_wheel` on the feature branch, and the version of wheel file built is `0.0.0rc1` instead of `0.0.0b1`. I am a 100% sure that I am running setup tools on the feature branch. 
Here is the snippet for setuptools-git-versioning configuration in my `setup.py` file:
`    version_config={
        "template": "{tag}",
        "dev_template": "{tag}",
        "dirty_template": "{tag}",
        "version_callback": None,
        "version_file": None,
        "count_commits_from_version_file": False,
        "branch_formatter": None,
    }, 
    setup_requires=["setuptools-git-versioning"]
`
My issue here is that setuptools-git-versioning is NOT recognizing the latest Git tag, and I don't understand why. 
I need help resolving this issue.

**Comment by dhathris** [comment]
Upon further investigation, I realized it's because of the command used to retrieve latest git tag, `git tag --sort=-version:refname --merged`. This command is asking for tags in reverse lexicographical order and hence the result I am observing. Is there a way to provide an option to choose instead to get the chronological ordering of the tags and get the latest tag based on chronological order?

**Comment by dolfinus** [comment]
Hi.

Could you please check v1.6.0?

**Comment by dhathris** [comment]
Yes, version v1.6.0 is working in chronological order for tags. Thanks.
