### ISSUE TITLE
Sorting broken for annotated tags

### ISSUE THREAD

**Issue by Balonbal** [dolfinus/setuptools-git-versioning#23]
Hi, we are using this project to version a project with annotated tags, and the latest update broke the versioning. The recent change to sort by date for #22 changed the tags sorting to consider the `committerdate` of the tag. This field does not exist for annotated tags, as they are a separate object from the commit. Based on this thread https://stackoverflow.com/a/34919313 I would suggest changing to `creatordate`, which works for both annotated and lightweight tags. The previous sort condition `version:refname` also worked fine for us, so maybe consider having the sorting configurable?

Thanks

**Comment by dolfinus** [comment]
Hi.

Please check the v1.6.1 release.

**Comment by Balonbal** [comment]
Awesome, it works now, thank you!

**Comment by dolfinus** [comment]
I've also added a way to pass sorting column through the config dict.
