### ISSUE TITLE
Add option to parse tag

### ISSUE THREAD

**Issue by darkdragon-001** [dolfinus/setuptools-git-versioning#31]
We have our git tags in the form of `release/x.y.z`. Would be nice if one could specify a regex to extract the version from the tag (e.g. like [`tag_regex` in pypa/setuptools_scm](https://github.com/pypa/setuptools_scm).

**Comment by dolfinus** [comment]
Hello.

Sorry for late response.
I'm going to add a `branch_callback` option to the package. But before I should add tests to cover existing functions, just to be sure that my changes will not affect a previous workflow.

**Comment by dolfinus** [comment]
Tests are in the master branch now, going to implement this feature

**Comment by dolfinus** [comment]
I've added new `branch_formatter` option in latest release v1.8.0.
You can pass here regexp, e.g. `release\/(?P<branch>.*)`, or callback function which should accept one argument with original branch name and return formatted one.

Here is a documentation with an example: https://setuptools-git-versioning.readthedocs.io/en/latest/options/branch_formatter.html
