### ISSUE TITLE
Slightly streamlining the documentation

### ISSUE THREAD

**Issue by Bloodmallet** [dolfinus/setuptools-git-versioning#42]
I noticed some slight inconsistent structures across multiple similar descriptions in the new documentation. I'd like to provide that. Would that be ok for you?
You added a contributing file, but it is empty. Should I pay attention to something specific?

**Comment by dolfinus** [comment]
Hello.

Sure, PRs are welcome.

Considering the contributing file, I'm going to fill it up a bit later. There will be some general information about testing, cloning the repo and so on.

**Comment by dolfinus** [comment]
Hi. Any updates here?

**Comment by Bloodmallet** [comment]
Sorry about the delay. It's quite hectic here. I'm closing this ticket and will open a PR when I have the time. Idle tickets aren't helpful.

About the raised question: when I checked the documentation after your published it , I found some style difference, like order of explanations, the way parameters were described, etc. Maybe those were already fixed in the meantime.
