### ISSUE TITLE
Building in a repo without tags, this plugin does nothing except setting "starting_version"

### ISSUE THREAD

**Issue by jonaseck2** [dolfinus/setuptools-git-versioning#53]
In a repo without tags, following the instructions to add setuptools_git_versioning to my setyp.py makes no difference:

```python
setuptools.setup(
...
    setuptools_git_versioning={
        "enabled": True,
    },
    setup_requires=["setuptools-git-versioning"],
)
```

```sh
python -m build
```

```output
Successfully built mypackage-0.0.1.tar.gz ...
```

Setting starting_version changes the package version, but that's the only setting that makes a difference.

Adding a semver tag to the repo and building yields the expected results:

```sh
git tag 0.0.0
python -m build
````

```output
Successfully built package-0.0.0.post0+git.d4b0e450.dirty.tar.gz ...
```

Either document that an initial semver tag is a prerequisite or support building without any tags in the repo

**Comment by dolfinus** [comment]
If you do not have any tag in a current branch, you can use [File-based versioning schema](https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/file/index.html)
