### ISSUE TITLE
How to get version from python scripts?

### ISSUE THREAD

**Issue by belonesox** [dolfinus/setuptools-git-versioning#55]
How to get version from python scripts?

For «normally» versioned packages we ask `__version__`
```
import numpy as d;print(d.__version__)
```

How to do this for «setuptools-git-versioning-ed» packages?

**Comment by dolfinus** [comment]
Hi.

As `Limitation` section in the Readme says:
```
Currently does not support exporting version to file for runtime use
```

You can run `python setup.py --version` to get the current version, and then write it to a file or script, before backing it into a package. But there is no builtin option for that
