### ISSUE TITLE
Is there a way to get the currently computed version in a pyproject.toml build?

### ISSUE THREAD

**Issue by sztomi** [dolfinus/setuptools-git-versioning#58]
When using setup.py, I can do

```
python3 setup.py --version  
```

Is there a way to do the same for a pyproject.toml build? `setuptools_scm` solves this by providing a `__main__`:

```
python3 -m setuptools_scm
```

**Comment by dolfinus** [comment]
Hi.

I've released v1.10.1 with such a feature, supporting both module (`python -m setuptools_git_versioning`) and script (`setuptools-git-versioning`) calls.
Please check.

**Comment by sztomi** [comment]
Thanks, that seems to work. But would it be possible to make it work regardless of using setup.py or pyproject.toml? If all else fails, it could runpy it maybe?

**Comment by dolfinus** [comment]
I need to check this

**Comment by dolfinus** [comment]
Why don't just run `python setup.py --version` if you're using `setup.py`? Please describe the case

**Comment by sztomi** [comment]
@dolfinus the use-case is a jenkins build template for python projects. The template does not know in advance if the concrete build will use setup.py or pyproject.toml. This is my current workaround:

```py
from pathlib import Path
from setuptools_git_versioning import version_from_git


if __name__ == "__main__":
  setup_py = Path("setup.py")
  pyproject = Path("pyproject.toml")
  if setup_py.is_file():
    from distutils.core import run_setup
    dist = run_setup(str(setup_py), stop_after="init")
    print(version_from_git(dist))
  elif pyproject.is_file():
    print(version_from_git())
  else:
    raise RuntimeError(
      "Mom, can we sane package management?\n"
      "We have sane package management at home\n"
      "Sane package management at home:"
    )
```

**Comment by dolfinus** [comment]
I've released v1.11.0, now `setuptools-git-versioning` script tries to load both `setup.py` and `pyproject.toml`. Please check

**Comment by sztomi** [comment]
Thank you so much! It seems to work as expected for both setup.py and pyproject.toml repos. It displays a traceback for non-compliant versions though. I think that's useful output, but maybe it would be better to only show that if some flag was passed (like `--validate`) - just my 2c. But this solves my problem already, and thank you for addressing it so quickly, I appreciate it.

```
/home/tamas/work/grabdeps/.venv/lib/python3.10/site-packages/setuptools/dist.py:507: UserWarning: The version specified ('7.1.2210121431.dev0_dirty') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tamas/work/grabdeps/.venv/lib/python3.10/site-packages/setuptools_git_versioning.py", line 647, in <module>
    __main__()
  File "/home/tamas/work/grabdeps/.venv/lib/python3.10/site-packages/setuptools_git_versioning.py", line 643, in __main__
    print(main(root=namespace.root).public)
  File "/home/tamas/work/grabdeps/.venv/lib/python3.10/site-packages/setuptools_git_versioning.py", line 592, in main
    return Version(result)
  File "/home/tamas/work/grabdeps/.venv/lib/python3.10/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '7.1.2210121431.dev0_dirty'
```

**Comment by dolfinus** [comment]
The whole idea of this package is to generate version numbers compatible with PEP-440. `7.1.2210121431.dev0_dirty` is not compatible, so it cannot be used as version number, and `setuptools` will complain about that too. Why do you need to disable verification?

**Comment by sztomi** [comment]
There is utility to this package without PEP compatibility in my opinion (in the form of version templates that can use git tags etc. for formatting). The command line output is difficult to use in integrations if its contents are either a version number or a long traceback.

**Comment by dolfinus** [comment]
PyPI uses PEP-440, as well as pip, setuptools, and all other packaging-related tools. Even if you disable validation, you will not be able to build or push package with such a version

**Comment by sztomi** [comment]
This is an internal package and the registry is not pypi (it's hosted in Artifactory). But I wouldn't push a dirty package anyway so I don't mean to say that this is a blocker for me in any way. Just a general observation.

**Comment by dolfinus** [comment]
Ok, closing then
