### ISSUE TITLE
Handle multiple product tags in a monorepo

### ISSUE THREAD

**Issue by vortechs2000** [dolfinus/setuptools-git-versioning#68]
Hey there - I have a monorepo that has multiple products' tags.  They are all prefixed with the product name/path like `releases/team/project/{version}` and I'd like to be able to just pull the '{version}' bit out when building a particular package.   Currently I just get whatever tag was created most recently, and it almost never corresponds to the package I'm building.

I've hacked in a `tag_prefix` config option and would be willing to push it here as a PR if you're interested in taking it, and/or I'm open to other ideas for how to manage this.

**Comment by dolfinus** [comment]
Hi.

Why to you tag the whole monorepo with a tag which correspond to some part of the repo instead the entire product?

**Comment by dolfinus** [comment]
#69 is merged, I've just released 1.13.0
