### ISSUE TITLE
Failed test test_substitution_timestamp due to race condition

### ISSUE THREAD

**Issue by andreas-schwab** [dolfinus/setuptools-git-versioning#71]
```
FAILED tests/test_integration/test_substitution.py::test_substitution_timestamp[{tag}.post{timestamp:}-{tag}.post{}-<lambda>]
=================================== FAILURES ===================================
__ test_substitution_timestamp[{tag}.post{timestamp:}-{tag}.post{}-<lambda>] ___

repo = '/tmp/pytest-of-abuild/pytest-0/test_substitution_timestamp__t1/6f4e3e3602eaa4e5daaa1a12a84539e66a34d71aee7dd17f2c1ffc3f5e075de7'
template = '{tag}.post{timestamp:}', fmt = '{tag}.post{}'
callback = <function <lambda> at 0x3fba967160>

    @pytest.mark.parametrize(
        "template, fmt, callback",
        [
            ("{tag}.post{timestamp}", "{tag}.post{}", lambda dt: (int(dt.strftime("%s")) // 100,)),
            ("{tag}.post{timestamp:}", "{tag}.post{}", lambda dt: (int(dt.strftime("%s")) // 100,)),
            ("{tag}.post{timestamp:%s}", "{tag}.post{}", lambda dt: (int(dt.strftime("%s")) // 100,)),
            (
                "{timestamp:%Y}.{timestamp:%m}.{timestamp:%d}+{timestamp:%H%M%S}",
                "{}.{}.{}+{}",
                lambda dt: (dt.year, dt.month, dt.day, dt.strftime("%H%M")),
            ),
            (
                "{tag}.post{ccount}+{timestamp:%Y-%m-%dT%H-%M-%S}",
                "{tag}.post{ccount}+{}",
                lambda dt: (dt.strftime("%Y.%m.%dt%H.%M"),),
            ),
            # unknown substitution
            ("{tag}+git.{timestamp:%i}", "{tag}+git.i", lambda x: []),
            # pure string
            ("{tag}+git.{timestamp:abc}", "{tag}+git.abc", lambda x: []),
        ],
    )
    def test_substitution_timestamp(repo, template, fmt, callback):
        create_setup_py(repo, {"template": template})
        create_tag(repo, "1.2.3")
    
        value = fmt.format(tag="1.2.3", ccount=0, *callback(datetime.now()))
        pattern = re.compile(r"([^\d\w])0+(\d+[^\d\w]|\d+$)")
        while True:
            # leading zeros are removed even in local part of version
            new_value = pattern.sub(r"\1\2", value)
            if new_value == value:
                break
            value = new_value
    
>       assert new_value in get_version_setup_py(repo)
E       AssertionError: assert '1.2.3.post16678291' in '1.2.3.post1667829202'
E        +  where '1.2.3.post1667829202' = get_version_setup_py('/tmp/pytest-of-abuild/pytest-0/test_substitution_timestamp__t1/6f4e3e3602eaa4e5daaa1a12a84539e66a34d71aee7dd17f2c1ffc3f5e075de7')

tests/test_integration/test_substitution.py:157: AssertionError
```

**Comment by dolfinus** [comment]
Please fix the issue format

**Comment by dolfinus** [comment]
Please provide context - Python version, OS, `git` version

**Comment by andreas-schwab** [comment]
This is all irreleveant.  It's a very simple race condition: the calls to datetime.now in test_substitution_timestamp and in _substitute_timestamp may return timestamps in different 100 second intervals, if the system time happens to be right at the edge of such an interval.  This must be taken into account.

**Comment by dolfinus** [comment]
Why then this issue is not being reproduced in CI builds which are performed on Windows, MacOS and Linux with Python versions from 3.7 to 3.11?
I need information about your environment to get reproducible test failure.

**Comment by dolfinus** [comment]
If you don't care about providing the info I need to reproduce build, and don't even care about the issue description formatting, why should I care about fixing the issue which is reproduced on your environment only?

**Comment by andreas-schwab** [comment]
If you don't care about making your tests work correctly in presence of races you are not doing your job.

**Comment by dolfinus** [comment]
- There is no race condition. The test is checking that if substitution uses current datetime, and format is a unix timestamp, tool should produce an expected result. Test can fail if time between generating the string used for comparison and executing a command with `subprocess` is larger than some value. But tests are not failing on CI builds, on my laptop and on environment of users who made pull requests to this rep o before. This could be something on your environment which slows down the command, causing the test failure, but I have no information about your environment at all, and you refused to provide this information.
- This is just a test, this is not a part of a package, it's not causing any issues while using this package. `This must be taken into account.` - I don't think so.
- This repo is my hobby project, not my job. I do not owe anything to anyone

**Comment by andreas-schwab** [comment]
You are wrong, the race is present in *every* environment.

**Comment by dolfinus** [comment]
No proof - no solution

**Comment by andreas-schwab** [comment]
Just run the test often enough, it will fail eventually.
