### ISSUE TITLE
0.0.1 version reported by windows users

### ISSUE THREAD

**Issue by bryevdv** [dolfinus/setuptools-git-versioning#75]
A few folks setting up Bokeh development environments report getting version `0.0.1` after following our setup instructions. As far I a can remember this has only affected windows users, and core devs have not yet been able to reproduce. A very responsive user has been posting information here:

* https://github.com/bokeh/bokeh/discussions/12763

Is there something else we can do to help debug this? As far as I can tell all the versions of build dependencies that get installed in the isolated build, and also the version of git, are the same as my OSX system where things are working.

**Comment by bryevdv** [comment]
Further back and forth seems to indicate that however they have cloned left the repo without any tags present. So I think that https://github.com/dolfinus/setuptools-git-versioning/issues/53#issuecomment-1094683604 would explain, then?

**Comment by dolfinus** [comment]
Hi.

Yes, without any tags in the repo setuptools-git-versioning uses starting_version as a fallback. Default value is 0.0.1: https://setuptools-git-versioning.readthedocs.io/en/stable/options/starting_version.html

**Comment by bryevdv** [comment]
👍 this an probably be closed then. Will need to figure out why none of the existing tags show up in their clone but that's not an issue for here.

**Comment by dolfinus** [comment]
In case of using branches without tags, you can use version_file option to read initial version from a file: https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/file/version_file.html

**Comment by bryevdv** [comment]
The branches do have tags. For some reason, when cloning on windows only, the tags are missing.
