### ISSUE TITLE
Support overriding version from environment

### ISSUE THREAD

**Issue by mweinelt** [dolfinus/setuptools-git-versioning#77]
We at nixpkgs package python projects from GitHub by pulling their tarball, which is much quicker than doing a full or bare git checkout. Subsequently, we don't have a Git repo that `setuptools-git-versioning` could infer the version from.

With setuptools-scm there is an environment variable `SETUPTOOLS_SCM_PRETEND_VERSION` through which the version can be explicitly. Adding support for such an escape hatch would be appreciated.

**Comment by dolfinus** [comment]
Hi.

Could the repo maintainer create [version_file](https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/file/version_file.html)? It can be used when tags are missing.

**Comment by dolfinus** [comment]
I've added recommendation to use `version_file` as default schema: https://setuptools-git-versioning.readthedocs.io/en/latest/schemas/file/index.html

**Comment by mweinelt** [comment]
Thanks, I apparently forgot to check back in.
