### ISSUE TITLE
wrong toml section for zip-safe

### ISSUE THREAD

**Issue by cclecle** [dolfinus/setuptools-git-versioning#78]
In the doc:
[setuptools-git-versioning.readthedocs.io](https://setuptools-git-versioning.readthedocs.io/en/stable/runtime_version.html)

It is stated **zip-safe** must sit in **tool.setuptools.package-data** section.
But setuptools want it to be in **tool.setuptools** section.

**Comment by dolfinus** [comment]
Hi.

Thank you, fixed in 1.13.3
