### ISSUE TITLE
Wrong ccount on Windows

### ISSUE THREAD

**Issue by shortsnake** [dolfinus/setuptools-git-versioning#8]
On Windows the ccount is incorrectly calculated to be the number of commits from the beginning of the repository and to HEAD. This is due to the `^` character being a escape character in the command prompt shell on Windows (since `shell=True` is used to `subprocess`).

https://github.com/dolfinus/setuptools-git-versioning/blob/14a4adc6c93e33b5acc3098869c1f60cc238a5c2/setuptools_git_versioning.py#L86

By quoting the name argument to git everything works as expected: `\"^{name}\"`

**Comment by dolfinus** [comment]
Hi.

Thank you for a fix. I've applied it into master branch and released v1.2.10, please check.

**Comment by shortsnake** [comment]
Works correctly with both cmd and powershell on Windows now. Thanks.
