### ISSUE TITLE
Feature/Fix: allow to search tag not only in current branch

### ISSUE THREAD

**Issue by cclecle** [dolfinus/setuptools-git-versioning#80]
In some CI/CD use-cases, relevant tag might not be in the current branch (--no-ff workflow)
So setuptools-git-versionning fails to find it as it is only looking at the current branch.

Exemple of workflow failing with current implementation:

        DEV           0.0.1   0.0.1.pos1   0.0.1.post2                    0.0.1.post3   <- oups !
        MASTER                                                 1.0.0
        
What would be expected:

        DEV           0.0.1   0.0.1.pos1   0.0.1.post2                      1.0.0.post1  <- well in order :)
        MASTER                                                 1.0.0

Is that possible to add a global available in setup (.toml included) allowing us to search in all branch ? (or having a list)

Exemple of implementation (with no error handling :) ):

      if same_branch is True:
          res = _exec("git describe --tags --first-parent --abbrev=0")
      else:
          res = _exec("git rev-list --tags --date-order --max-count=1")
          if len(res)==1:
              res = _exec(f"git describe --tags {res[0]}")
      return res[0]

Edit, other exemple to get all tags (ordering might need adaptation..):

        if same_branch  is True:
            currentBranch = _exec("git rev-parse --abbrev-ref HEAD")
            return list(reversed(_exec(f"git tag --merged {currentBranch[0]} --sort={sort}")))
        return list(reversed(_exec(f"git tag -l --sort={sort}")))

**Comment by dolfinus** [comment]
Hi.

Could you please describe those use cases in mire details?

**Comment by cclecle** [comment]
Ok will try:

**Context:** a Git repository with 2 branch: dev and master + a jenkins server for CI/CD

**Workflow summuary:**

1. I work in dev branch, pushing commit when needed
2. This trigger a **dev** job on jenkins, lots of things are happening, but at last stage it is pushing a release on gitea, which create a tag (X.X.X.postY) [ _those tags are then ignored thanks to the filter feature of setuptools-git-versioning_]
3. (Maybe more dev push so more version / tag (Y++) )
4. When everything is fine, I merge (no fast-forward strategy) on **master** with a full version tag: Z.Z.Z, almost same jenkins process to release a version
...
... => some bugs or new features to implement !
...
5. I update my code like in step 2 or 3, so pushing on **dev** branch 

**Problem is here:** as setuptools-git-versioning is only looking on dev branch, it can not see tag Z.Z.Z from master **branch**.
So both base release numer and post release increment are wrong.

This is the only thing I need to fix to make my workflow working... :(
I had to switch to setuptools_scm because of that issue...

_**fun fact**: I am actually working on a version parser / lister helper lib for my CI/CD needs... But no plan to implement a setuptools interface :) Sample code comes from it. ([pygitversionhelper](https://chacha.ddns.net/gitea/chacha/pygitversionhelper))_

**Comment by dolfinus** [comment]
Why not use https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/file/dev_release_file.html?

**Comment by dolfinus** [comment]
The main issue with the approach of using tags from another branch is that tags are not related to any changes in the dev branch. You can tag a commit in the main branch, and this commut was never added to dev branch, so using this tag while generating the version number can produce unexpected result.

Also if you need to go back to some old commit, and build some artifact (package, etc) from the corresponding source code, you'll instead get the latest tag from the main branch, which is also unexpected.

**Comment by dolfinus** [comment]
> I guess you are doing mostly fast-forward merges ?

No, I'm using merge commits.

> I do not want a version file

What are the drawbacks of this strategy?

**Comment by cclecle** [comment]
Ok,  merge commit == no-ff.

I do not want version file because... this is the point of using git versionning :smile: .

Seriously, I only put merge commit in master, so I will have to put final version string in dev commit.
But then when I will merge dev in master it will create another new commit.
So lets say I commited version.. 1.2.3 into dev, then the next verison in master will be ... 1.2.3.post1.
Because remember I create release in both dev and master, and if I want a release i need a tag and I can not have 2 same tags in 2 différent commits (gitea is linking releases to tags).

But will take it a try, maybe there is something I missed or misunderstood...

**Comment by dolfinus** [comment]
> I commited version.. 1.2.3 into dev

> Because remember I create release in both dev and master

> I can not have 2 same tags in 2 différent commits

[Here](https://github.com/dolfinus/setuptools-git-versioning/issues/80#issuecomment-1475416732) you've said that you push to dev branch tags like `X.X.X.postY` and push tags like `Z.Z.Z` to master.

**Comment by cclecle** [comment]
In last message I was actually describing what I _would_ have to do to apply what you tell me, and explaining why I think it will not fit my needs. 
Then, what you are referenciong _here_ is what I _do_ do.

Basically, you are telling me that I need to do version modification in the merge commit dev -> master.
And I said n,o I dont want that workflow, because 1st I do not want any version file, and second I want my merge to be only releasing, not a single difference. ( And 3rd I ll be honest, I dont want to change my workflow wich fit perfectly my needs).

**Comment by dolfinus** [comment]
> Basically, you are telling me that I need to do version modification in the merge commit dev -> master.

**Comment by dolfinus** [comment]
> Basically, you are telling me that I need to do version modification in the merge commit dev -> master.

I'm trying to understand your workflow, but I see conflicts between your description and how git works.

> I can not have 2 same tags in 2 différent commits

Why do you need to do that?
