### ISSUE TITLE
Support git archival export-subst

### ISSUE THREAD

**Issue by DrYak** [dolfinus/setuptools-git-versioning#82]
## context

Currently, when there is no `.git` directory available, setup-git-versioning allows the option `version_file` which allows a file whose content is picked up _verbatim_ as the version string. This option makes life much better, but still has two major drawbacks:

 - it MUST be PEP 440 compliant
 - it still needs to be manually filled, so it needs to be kept in sync with the git tagging, so it kind of defeats the purpose of git-versioning for those who use it for "_Git is always the ground truth and single source for version numbers_"
 
There is a partial solution for that (keeping the file in sync with Git tags automatically): most of the time tarballs without a `.git` directory are created by `git archive` and that one supports the export substitution attribute to automatically fill files.

So currenlty, it's already possible to create a `VERSION` file that is checked into git with something along those lines:
```text
$Format:%(describe:tags=true,abbrev=0,match=[0-9]*)$
```
and then set .git_attribute:
```text
VERSION export-subst
```
with that the VERSION file will be automatically filled when making tarballs (e.g.: downloading .tar.gz from GitHub).

BUT:

- This only works with tags that are exactly PEP 440 compliant versions (e.g.: `0.3.0`) and not the much more common `v` prefix (e.g.: `v0.3.0`)
   - hence the `match=[0-9]*` glob filter.
- It loses any other information beyond the tag, because all the additional information provided by `git describe` (number of commits, dirty, etc.) is not PEP 440 compliant
   - we're forced to use `abbrev=0` option of git describe.

A much more elegant solution adopted by other similar tools is to use a file with much more informations autofilled by git archive upon exporting a tarball.
e.g.:
- `poetry-dynamic-versioning` supports [providing a JSON file that is export subst'ed](https://github.com/mtkennerly/dunamai#vcs-archives).
- `setuptools_scm`  supports [providing a txt file that is export sibst'ed](https://github.com/pypa/setuptools_scm#git-archives)

These tools can then find all the informations they need and that would have been provided by `git describe`, etc. and they can use the content of those file to generate a fully version description as they would have done with git.

## feature request

It would be great if, in addition to supporting "_copy-paste verbatim the content of a file as a version string_", `setuptools-git-versioning` could also support some forms of "_read data from a toml file, and process normal version string building, as if it was provided by executing `git`_". (or a JSON file, or whatever the setup-git-versioning devs find the most appropriate).

Technically, this could be achieved already now by using a call back function, that:
- loads the toml/JSON/whatever file
- feed the file into whatever internal function of setup-git-versioning is normally used to process the output of git.

But this method:
- would require using the legacy back-end of setuptools, which opens its own can of worms.
- would be tapping into functions which aren't public APIs.

**Comment by dolfinus** [comment]
Hi.

You can create `version.py` and created here function or attribute with any content you want, returning version number. And then pass function/attribute full name to [version_callback](https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/callback/version_callback.html).

**Comment by dolfinus** [comment]
Use something like https://github.com/mtkennerly/dunamai
