### ISSUE TITLE
GitLab workaround, for shallow clone

### ISSUE THREAD

**Issue by pfbuxton** [dolfinus/setuptools-git-versioning#83]
Hello,

By default GitLab does a **shallow checkout** within runners, see [GitLab documentation on runners](https://docs.gitlab.com/ee/ci/large_repositories/index.html#shallow-cloning)

Once this number of commits is reached it is not possible to figure out which tag the commit belongs to.
```terminal
git describe
fatal: No tags can describe 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

This can be fixed by adding the following to `.gitlab-ci.yml`:
```yml
variables:
  GIT_DEPTH: 0
```

Might be worth adding to documentation?

btw- `setuptools-git-versioning` is an amazing project ❤️

**Comment by dolfinus** [comment]
Hi.

Thank you, added to documentation.
