### ISSUE TITLE
Add full sha to list of outputs

### ISSUE THREAD

**Issue by pjongeneel** [dolfinus/setuptools-git-versioning#9]
Hi, please add tag_sha in your code (I think that's the full sha) to the list of outputs, perhaps as full_sha?

Thank you!

**Comment by pjongeneel** [comment]
Sorry it would be head_sha.

Would look like this
`
return t.format(sha=short_sha, full_sha=head_sha, tag=tag, ccount=ccount, branch=branch)
`

**Comment by dolfinus** [comment]
Hello.

Please try v1.3.0.
